# dbt Profiles Configuration
# Uses environment variables for secure credential management

etl_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('TARGET_DB_HOST', 'target_db') }}"
      port: "{{ env_var('TARGET_DB_PORT', '5432') | int }}"
      user: "{{ env_var('TARGET_DB_USER', 'target_user') }}"
      password: "{{ env_var('TARGET_DB_PASSWORD', 'target_pass') }}"
      dbname: "{{ env_var('TARGET_DB_NAME', 'target_dwh') }}"
      schema: raw
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10

    prod:
      type: postgres
      host: "{{ env_var('TARGET_DB_HOST') }}"
      port: "{{ env_var('TARGET_DB_PORT') | int }}"
      user: "{{ env_var('TARGET_DB_USER') }}"
      password: "{{ env_var('TARGET_DB_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_DB_NAME') }}"
      schema: raw
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
