version: 2

models:
  - name: int_orders_enriched
    description: Orders joined with customer information for easier analysis
    columns:
      - name: order_id
        description: Unique identifier for the order
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Reference to the customer
        tests:
          - not_null
      - name: customer_name
        description: Name of the customer who placed the order
      - name: customer_email
        description: Email of the customer who placed the order

  - name: int_order_items_enriched
    description: Order line items joined with product details
    columns:
      - name: order_item_id
        description: Unique identifier for the order item
        tests:
          - unique
          - not_null
      - name: order_id
        description: Reference to the order
        tests:
          - not_null
      - name: product_id
        description: Reference to the product
        tests:
          - not_null
      - name: product_name
        description: Name of the product ordered
      - name: line_total
        description: Total for this line item
        tests:
          - not_null
